# YOLO数字检测器配置文件
# 此文件包含所有可配置的参数，用于调整检测器的行为

yolo_detector:
  # 模型配置部分
  # -----------------------------
  model_path: "/home/royal/catkin_ws/src/yolo_digit_detector/models/best.pt"  # YOLO模型文件的绝对路径
  conf_threshold: 0.4    # 置信度阈值：只有检测结果置信度大于此值的才会被接受
  iou_threshold: 0.45    # IOU阈值：用于非极大值抑制，过滤重叠的检测框，值越大保留的框越多
  
  # 图像处理配置部分
  # -----------------------------
  image_width: 640       # 输入图像的宽度，需要与模型训练时的输入尺寸匹配
  image_height: 480      # 输入图像的高度，需要与模型训练时的输入尺寸匹配
  
  # 发布频率配置
  # -----------------------------
  publish_rate: 10.0     # 检测结果发布的频率，单位Hz，即每秒发布多少次结果
  
  # 调试和可视化选项
  # -----------------------------
  debug: true            # 是否开启调试模式，开启后会打印更多调试信息
  visualize: true        # 是否可视化检测结果，开启后会显示带有检测框的图像窗口 